### ISSUE TITLE
请问mac上如何运行

### ISSUE THREAD

**Issue by 02VC7** [yourtion/30dayMakeOS#1]
如题。。。

**Comment by yourtion** [comment]
过段时间，最近在研究中，因为要改Makefile什么的，打算重新开个项目做Linux跟Mac的兼容还有继续开发

**Comment by sharkaz** [comment]
这里可以下载到z_tools的osx版。
http://shrimp.marokun.net/osakkie/wiki/tolsetOSX/

另外，我在Mac上是用VirtualBox代替qemu

**Comment by yourtion** [comment]
@sharkaz Thanks，但是主要是 day27 之后改了目录结构，很多 Makefile 的内容需要重新写，这个我也正在处理。

我重新开了这个项目在改进：https://github.com/yourtion/YOS
