### ISSUE TITLE
请问日语和乱码您是怎么解决的？

### ISSUE THREAD

**Issue by Wrecksoul** [yourtion/30dayMakeOS#2]
我在网上找到的《30天自制操作系统》这本书附件部分，作者是日本人而且注释的也是日文，并且编码不是UTF-8，请问您有中文版的附件吗？

**Comment by yourtion** [comment]
这个项目就是对所有对源码进行中文注释了

![image](https://user-images.githubusercontent.com/1475301/34192738-e212f840-e58a-11e7-855b-1c933f1a5952.png)

**Comment by Wrecksoul** [comment]
授人以鱼不如授人以渔啊。我想知道您的中文注释是怎么来的。是否有更多没在这个项目里面的资料。

**Comment by yourtion** [comment]
哦，原来是这样的意思啊，Sorry啊～～这本书有本中文版本，我是在多看上买的：http://www.duokan.com/book/11722

然后我一边看中文书还有原版的源码，然后根据书中的注释还有代码一步步写的。

**Comment by Wrecksoul** [comment]
可是，我下载的源码是这样的乱码：
```
; hello-os
; TAB=4

		ORG		0x7c00			; ‚±‚ÌƒvƒƒOƒ‰ƒ€‚ª‚Ç‚±‚É“Ç‚Ýž‚Ü‚ê‚é‚Ì‚©

; ˆÈ‰º‚Í•W€“I‚ÈFAT12ƒtƒH[ƒ}ƒbƒgƒtƒƒbƒs[ƒfƒBƒXƒN‚Ì‚½‚ß‚Ì‹Lq

		JMP		entry
		DB		0x90
		DB		"HELLOIPL"		; ƒu[ƒgƒZƒNƒ^‚Ì–¼‘O‚ðŽ©—R‚É‘‚¢‚Ä‚æ‚¢i8ƒoƒCƒgj
		DW		512				; 1ƒZƒNƒ^‚Ì‘å‚«‚³i512‚É‚µ‚È‚¯‚ê‚Î‚¢‚¯‚È‚¢j
		DB		1				; ƒNƒ‰ƒXƒ^‚Ì‘å‚«‚³i1ƒZƒNƒ^‚É‚µ‚È‚¯‚ê‚Î‚¢‚¯‚È‚¢j
		。。。

; ƒvƒƒOƒ‰ƒ€–{‘Ì
```
应该用什么编码格式打开，不过，这个就算打开不是乱码应该也是日文的吧。

您是有中文版的资源还是凑合着看这个代码再加上书上的中文注释的呢？

**Comment by yourtion** [comment]
你下载的什么源码是乱码？我使用SublimeText打开原来日文的源码是正常的。

源码没有中文资源，都是原来的日文版本，然后加中文书

**Comment by Wrecksoul** [comment]
可能是我打开的时候跟他保存时使用的编码不一致所以乱码吧 。不过即使不乱码 ，日语我也看不懂。谢谢你了。我的疑问没有了，我现在要关闭ISSUE了。

**Comment by sky5454** [comment]
![image](https://user-images.githubusercontent.com/12370628/58414151-292ca500-80ad-11e9-99e3-c30c6db31f97.png)
日文原版源码为Shift-JIS编码
换行符为Windows(CR LF)
