### ISSUE TITLE
路径不对

### ISSUE THREAD

**Issue by JosanSun** [yourtion/30dayMakeOS#4]
../z_tools/  所有路径都应该改为../tolset/z_tools

**Comment by yourtion** [comment]
![image](https://user-images.githubusercontent.com/1475301/45081531-f828d080-b129-11e8-9f7d-52c1be636f93.png)

**Comment by JosanSun** [comment]
还是不对啊。

cons.bat 只是启动了cmd，没有修改路径。

**Comment by sky5454** [comment]
> 还是不对啊。
> 
> cons.bat 只是启动了cmd，没有修改路径。

手动切换路径或者复制目录到指定位置，原书也是让读者自己手动复制的
