### ISSUE TITLE
你好，请问是日文原版光盘的翻译吗

### ISSUE THREAD

**Issue by sky5454** [yourtion/30dayMakeOS#7]
主要是想问问除了翻译，其他是否和原版光盘一致。☺另外谢谢你分享了这个项目

**Comment by crazyn2** [comment]
这我不知道，我这也是从网上找的，readme里面有说明

**Comment by sky5454** [comment]
好吧，另外，由于目录结构改变了，批处理文件里内容都需要更改了.....
例如：
```cmd
[CMD]>30dayMakeOS\01_day>..\z_tools\nask.exe helloos.nas helloos.img
The system cannot find the path specified.
```

**Comment by crazyn2** [comment]
其实他的文件是不全的，我也试了试。我推荐你用我找到的，在我的github仓库里，你搜索我的昵称就可以找到。

**Comment by sky5454** [comment]
> 其实他的文件是不全的，我也试了试。我推荐你用我找到的，在我的github仓库里，你搜索我的昵称就可以找到。

你好，我已经建立了[仓库](https://github.com/sky5454/30daysMakeOS-Origin-ISOfiles)
镜像是从网上下载的，使用文件对比工具，发现镜像里所有文件和CSDN的一样，应该是原版的

**Comment by yourtion** [comment]
不完全是原版，是阅读过程一边汉化源码，一边执行还有根据一些相关的内容进行代码的书写

**Comment by Dingchengfeng** [comment]
问一下，你们按键处理部分没有问题吗？运行第17天的程序，输入任意字母，输入框里会一直打印这个字母到结尾。之前这个问题不影响后续开发，就没管了，现在必须要解决了

**Comment by EndlessCheng** [comment]
原版光盘下载地址 https://www.ituring.com.cn/book/910 右侧随书下载

**Comment by VortexBlade** [comment]
> 问一下，你们按键处理部分没有问题吗？运行第17天的程序，输入任意字母，输入框里会一直打印这个字母到结尾。之前这个问题不影响后续开发，就没管了，现在必须要解决了

是使用中文输入法的原因，你切换成英文就可以了

**Comment by yourtion** [comment]
> > 问一下，你们按键处理部分没有问题吗？运行第17天的程序，输入任意字母，输入框里会一直打印这个字母到结尾。之前这个问题不影响后续开发，就没管了，现在必须要解决了
> 
> 是使用中文输入法的原因，你切换成英文就可以了

对，这个应该是跟输入法怎么给 qumu 有关，这块暂时没有做过多的处理
